name: Docker Image Build and Push

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'      
    branches:
      - dev
  workflow_dispatch:

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  IMAGE_NAME: rebuild-dndc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build Multi-Arch Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:latest-${{ env.GITHUB_SHA }}
          build-args: |
            --platform linux/amd64,linux/arm64,linux/arm/v7
            --progress plain
            --build-arg GITHUB_SHA=${{ env.GITHUB_SHA }}
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }}
            --build-arg VCS_REF=${{ env.VCS_REF }}

      - name: Publish to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
          docker push eafxx/rebuild-dndc:unraid-d
          docker push eafxx/rebuild-dndc:unraid-d-${{ env.GITHUB_SHA }}
