name: Docker Build Dev
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/*'        
    branches: 
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      run: |
         docker login -u $DOCKER_USER -p $DOCKER_PWD
    - uses: rlespinasse/github-slug-action@v2.x
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_SHA_SHORT }}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t eafxx/rebuild-dndc:unraid-d
        docker build . --file Dockerfile -t eafxx/rebuild-dndc:unraid-d-${{ env.GITHUB_SHA_SHORT }}
    - name: Docker Push
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}      
      run: |
        docker push eafxx/rebuild-dndc:unraid-d
        docker push eafxx/rebuild-dndc:unraid-d-${{ env.GITHUB_SHA_SHORT }}
